FROM apache/airflow:2.7.0

USER root

RUN apt-get update && apt-get install -y wget make gnupg && \
    wget -O - https://debian.neo4j.com/neotechnology.gpg.key | apt-key add - && \
    echo 'deb https://debian.neo4j.com stable 5' > /etc/apt/sources.list.d/neo4j.list && \
    apt-get update && apt-get install -y cypher-shell && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow


COPY dags/ /opt/airflow/dags/
COPY scripts/ /opt/airflow/scripts/
COPY quality/ /opt/airflow/quality/
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt
